apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ecommerce-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: artemcontainerregistry.azurecr.io/ecommerce-mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
            - name: MYSQL_DATABASE
              value: products_db
            - name: MYSQL_USER
              value: mysql
            - name: MYSQL_PASSWORD
              value: mysql
          ports:
            - containerPort: 3306
