services:
  postgres:
    image: postgres:16-alpine
    container_name: users-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-service
    ports:
      - "5432:5432"
    volumes:
      - ./sql/postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  mysql:
    image: mysql:8.4
    container_name: products-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_service
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - ecommerce-network
    hostname: mysql-host-productsmicroservice

  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro

  products-microservice:
    image: artemva/ecommerce-products-microservice:v1.0
    environment:
      - MYSQL_HOST=mysql-host-productsmicroservice
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ecommerce-network

  users-microservice:
    image: artemva/ecommerce-users-microservice:v1.0
    environment:
      - POSTGRES_HOST=users-service-db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - ecommerce-network
  
networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mongo_data:

